version: "3.3"
services:
  goWechat:
    image: yoyoo/wechat_go:v1
    pull_policy: missing
    hostname: go-wechat
    container_name: go-wechat
    restart: always
    ports:
      - 6666:8080
    volumes:
      - /home/ubuntu/soft/gin-demo/config.yaml:/app/config.yaml
    environment:
      - TZ=Asia/Shanghai

  redisServer:
    image: redis:6.2-alpine
    pull_policy: missing
    hostname: redis-server
    container_name: redis-server
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai   