AppName = "test go gin"
[Server]
  Host = ":9999"
  SsL = false
[Database]
  Driver = "mysql"
  Host = "127.0.0.1:3306"
  UserName = "root"
  Passwd = "123456"
  Schemal = "gin"
[Database.Pool]
  IdleMax = 100
  Idlemin = 10
  ReadTimeOut = 10000
  ConnectTimeout = 10000  