app_name = "gin demo"
[server]
host = ""
port = "8989"
[database]
host = "10.254.148.149:3306"
user = "root"
passwd = "5OKc8OVZFRAbfJ"
schema = "biz_data"
[k8sConf]
host = "https://10.10.10.1:6443"
bearerToken = "eyJhbGciOiJSUzI1NiIsImtpZCI6Ind4dVJNNHZsbzR3dWlVbHMzZ1lsSDdlbmNhM3RHV0c1Q1JLMGRaYzY5WlEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJ0ZXN0LXNhLXRva2VuLWhzNXJ2Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRlc3Qtc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJiYzI3MjNiYy1lOWZiLTQwNTQtODE2OS0xZGQxYTA4NjBkOGYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06dGVzdC1zYSJ9.Jcxz9_LET6-H4RfwQxVmkdgHPttmLlfBdVkNyMQGcNteb7BvixZU-LVX5sNW4B18Hb8vAA4bqyA_I0M0xP6-jD2x_lXFlqLZePNX0v3p4lbu42itySVL9OYr73h2bYdIZkCZh8bBO9cqhP3zzPg_6Fxwqq34OYlEj-MkeesUXaEdRXmxpt1AUL6crGbtUa0yaqH2_p4rJlsHCcZMBSUBj8c21_KVVoLMaCw_7UO4EDSG9xih_5GJyc-zYMFhsL_tqNPHhccVVIhbsP6IJaawfthlHIU2mt6gYZWf6IFUM4Rt-AAKFAQkBDeM2r-GYCB5wKCfdrSTj1zQCv9RetKxkw"